buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.6.0'
    }
}

repositories {
    google()
    mavenCentral()
}

apply plugin: qtGradlePluginType

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])
    implementation fileTree(dir: qtJarDir, include: ['*.jar'])
    implementation 'androidx.core:core:1.13.1'
    implementation 'androidx.annotation:annotation:1.8.2'
    implementation 'dev.rikka.shizuku:api:13.1.5'
    implementation 'dev.rikka.shizuku:provider:13.1.5'
}

android {
    buildFeatures {
        aidl true
        buildConfig true
    }

    namespace androidPackageName
    compileSdkVersion androidCompileSdkVersion
    buildToolsVersion androidBuildToolsVersion
    ndkVersion androidNdkVersion

    packagingOptions.jniLibs.useLegacyPackaging true

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = [qtAndroidDir + '/src', 'src', 'java']
            aidl.srcDirs = [qtAndroidDir + '/src', 'src', 'aidl']
            res.srcDirs = [qtAndroidDir + '/res', 'res']
            resources.srcDirs = ['resources']
            renderscript.srcDirs = ['src']
            assets.srcDirs = ['assets']
            jniLibs.srcDirs = ['libs']
        }
    }

    tasks.withType(JavaCompile) {
        options.incremental = true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    lintOptions {
        abortOnError false
    }

    aaptOptions {
        noCompress 'rcc'
    }

    signingConfigs {
        release {
            def keystoreFileProp = project.findProperty('starryKeystoreFile')
            if (keystoreFileProp != null && keystoreFileProp.toString().trim().length() > 0) {
                def keystoreFile = new File(keystoreFileProp.toString())
                storeFile keystoreFile
                storePassword project.findProperty('starryKeystoreStorePass') ?: ''
                keyAlias project.findProperty('starryKeystoreAlias') ?: ''
                keyPassword project.findProperty('starryKeystoreKeyPass') ?: ''
            }
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
        }
    }

    defaultConfig {
        applicationId androidPackageName
        versionCode 1
        versionName "1.0"
        resConfig "en"
        minSdkVersion qtMinSdkVersion
        targetSdkVersion qtTargetSdkVersion
        ndk.abiFilters = qtTargetAbiList.split(",")
    }
}
